base_url = "/"
title = "Venator"

default_language = "en"
compile_sass = true
generate_feed = true
feed_filename = "rss.xml"
build_search_index = false
taxonomies = [{ name = "tags" }]

[markdown]
highlight_code = true
highlight_theme = "ayu-mirage"
external_links_target_blank = true
external_links_no_referrer = true
smart_punctuation = true

[languages.fr]
title = "Venator"
taxonomies = [{ name = "tags" }]

[translations]
logo_text = "brack0.dev"

footer_powered_by = "Powered by"
footer_theme_by = "Theme inspired by"
footer_hosted_on = "Hosted on"

hero_title = "Venator"
hero_tagline = "The Backbone of Web Development against Confederacy of Node_modules"
hero_hello_there = "Hello there 👋 !"
hero_content_1 = "My name is "
hero_content_2 = "Denis Souron"
hero_content_3 = ". I am a developer, casual blogger & co-host of Front-end chronicles podcast."

lost = "Lost?"
page_doesnt_exist = "This page does not exist."

paginator_newer_posts = "Newer posts"
paginator_older_posts = "Older posts"

post_post = "post"
post_read_more = "Read more"
post_view_navigation_prompt = "Thanks for reading! Read other posts?"

tag_all_tags = "all tags"
tag_tag = "tag"
tag_tags = "tags"
tag_show_all_tags = "Show all tags"

[languages.fr.translations]
logo_text = "brack0.dev"

footer_powered_by = "Powered by"
footer_theme_by = "Theme inspired by"
footer_hosted_on = "Hosted on"

hero_title = "Venator"
hero_tagline = "The Backbone of Web Development against Confederacy of Node_modules"
hero_hello_there = "Hello there 👋 !"
hero_content_1 = "My name is "
hero_content_2 = "Denis Souron"
hero_content_3 = ". I am a developer, casual blogger & co-host of Front-end chronicles podcast."

lost = "Lost?"
page_doesnt_exist = "This page does not exist."

paginator_newer_posts = "Newer posts"
paginator_older_posts = "Older posts"

post_post = "post"
post_read_more = "Read more"
post_view_navigation_prompt = "Thanks for reading! Read other posts?"

tag_all_tags = "all tags"
tag_tag = "tag"
tag_tags = "tags"
tag_show_all_tags = "Show all tags"

[extra]
menu_items = [
    { name = "blog", url = "blog" },
    { name = "about me", url = "about" },

    { name = "github", url = "https://github.com/brack0", external = true },
    { name = "gitlab", url = "https://gitlab.com/Brack0", external = true },
]

# Optional: default image to use for OpenGraph.
#           If the page doesnt set og_image, use this one as fallback. Usefull
#           for indexes and taxonomies' pages.
#default_og_image = "static/ocean.jpg"
