base_url = "/"
title = "Venator"

default_language = "en"
compile_sass = true
generate_feed = true
feed_filename = "rss.xml"
build_search_index = false
taxonomies = [
    {name = "tags"}
]

[markdown]
highlight_code = true
highlight_theme = "ayu-mirage"
external_links_target_blank = true
external_links_no_referrer = true
smart_punctuation = true

[extra]
logo_text = "brack0.dev"

# The logo link - defaults to base_url.
#logo_home_link = "/take/me/away!"

# Author name: when specified, modifies the default
# copyright text. Apart from author, it will
# contain current year and a link to the theme.
#author = "My Name"

# menu is enabled by adding menu_items (optional)
menu_items = [
    { name = "blog", url = "/blog" },
    { name = "tags", url = "/tags"},
    { name = "archives", url = "/archives" },
    { name = "about me", url = "/about" },

    { name = "github", url = "https://github.com/brack0", newtab = true },
    { name = "gitlab", url = "https://gitlab.com/Brack0", newtab = true },
]

# Whether to show links to earlier and later (aka. higher/lower) posts
# on each post page (defaults to true).
enable_post_view_navigation = true

# The text shown at the bottom of a post,
# before earlier/later post links.
# Defaults to "Thanks for reading! Read other posts?"
post_view_navigation_prompt = "Thanks for reading! Read other posts?"

# Optional: Global favicon URL and mimetype.
#           Mimetype defaults to "image/x-icon".
#           The URL should point at a file located
#           in your site's "static" directory.
# favicon = "/favicon.png"
# favicon_mimetype = "image/png"

# Optional: default image to use for OpenGraph.
#           If the page doesnt set og_image, use this one as fallback. Usefull
#           for indexes and taxonomies' pages.
#default_og_image = "static/ocean.jpg"

hero_title = "Venator"
hero_subtitle = "The Backbone of Web Development against Confederacy of Node_modules"